Simplify mltk.sh
Rearrange the parameter list for easier parsing.

Spec files are optional and go last.
Try machine/mips/decoder.m as an example of a spec-less matcher.

diff --git a/frontend/mltk.sh.in b/frontend/mltk.sh.in
--- a/frontend/mltk.sh.in
+++ b/frontend/mltk.sh.in
@@ -1,94 +1,73 @@
-#!/bin/bash
-# Hopefully, the above is found in most systems
+#!/bin/sh
 #
+# This script is a wrapper to simplify generating decoders from .spec files
+# and a .m file.
 #
 # Copyright (C) 2000-2001, The University of Queensland
 # Copyright (C) 2000, Sun Microsystems, Inc
+# Copyright (C) 2017, Kyle Guinn
 #
-# See the file "LICENSE.TERMS" for information on usage and
-# redistribution of this file, and for a DISCLAIMER OF ALL
-# WARRANTIES.
-#
-#
-# This script is a wrapper to simplify generating decoders from .spec
-# files and a .m file.
-# This script uses features only found in the GNU bash shell.
-#
+# See the file "LICENSE.TERMS" for information on usage and redistribution of
+# this file, and for a DISCLAIMER OF ALL WARRANTIES.
 
-SCRATCH=/tmp/mltk.scratch.$$
-
-usage () {
-	echo "usage: $0 [-o output.cc] spec-files matcher-file";
-	exit;
-}
-
-# Clean up temp files if this script is interupted
-trap 'rm -f ${SCRATCH}; exit' 0 1 2 15
-
-# Check the invocation
-if [ $# -lt 4 ]; then
-	usage;
-fi
 
 # These 2 tools are configured (see configure.ac)
-TKML=@TKML@
+SML_TOOLKIT=@SML_TOOLKIT@
 UNGENERATE=@UNGENERATE@
 
+usage () {
+	echo "usage: $0 matcher-file [-o output.cpp] [spec-files]"
+	exit 2
+}
 
-# Set the matcher to be the last positional parameter and derive the
-# .cc file to be generated from it.
-MATCHER=${@:$#:1}
-MATCHER_DIR=`dirname ${MATCHER}`
-MATCHER_CC=`basename ${MATCHER} .m`
-MATCHER_CC="${MATCHER_DIR}/${MATCHER_CC}.cc"
+# Determine matcher filename.
+if [ $# -lt 1 ]; then
+	usage
+fi
+MATCHER="$1"
+shift
 
-# grab output filename
-if [ "${1}" = "-o" ]; then
-	shift
-	MATCHER_CC="${1}"
-	shift
+# Determine output filename.
+if [ $# -eq 1 -a "$1" = "-o" ]; then
+	usage
+elif [ $# -ge 2 -a "$1" = "-o" ]; then
+	OUTPUT="$2"
+	shift 2
+else
+	# Derive the output filename from the matcher.
+	OUTPUT="$(dirname "${MATCHER}")/$(basename "${MATCHER}" .m).cpp"
 fi
 
-# Build the command to be fed into the toolkit
-#CMD="val d = CC.matcher [\""
+# Build the list of spec files.
+SPECS=
+if [ $# -gt 0 ]; then
+	SPECS="\"$1\""
+	shift
+fi
+while [ $# -gt 0 ]; do
+	SPECS="${SPECS}, \"$1\""
+	shift
+done
+
+# Run the toolkit.
 # Norman wrote some 32 bit code for us, at great time expense to him, but
 # unfortunately, this seems to cause a memory explosion. The versions from
 # 4th Aug onwards have this problem. So for now, we use the 1st Aug version,
 # which doesn't have the 32 bit fixes, and we turn off the field fusion
 # optimisations (so it doesn't need the 32 bit code to match single sparc
 # return instructions, for example).
-CMD="val _ = GlobalState.Match.fuse := false; val d = CC.matcher [\""
-while [ $# -ne 2 ]; do
-
-	# Make sure the current file is a .spec file
-	if [ "${1%%.spec}" = "$1" ]; then
-		echo "bad suffix for \`$1': SLED files require the .spec suffix";
-		exit;
-	fi
-
-	# Make sure the current file exists
-	if [ ! -f $1 ]; then
-		echo "$1: no such file";
-		exit;
-	fi
-
-	# Add the current spec file to the command
-	CMD="${CMD}${1}\",\"";
-	shift;
-done
-CMD="${CMD}${1}\"];"
-shift
-CMD="${CMD} d \"${MATCHER}\";"
-
-# Run the toolkit
-eval "${TKML}" <<EOF
-	${CMD}
+eval "${SML_TOOLKIT}" <<EOF
+	val _ = GlobalState.Match.fuse := false;
+	val d = CC.matcher[${SPECS}];
+	d "${MATCHER}";
 EOF
+if [ ! -f "${MATCHER}.d" ]; then
+	exit 1;
+fi
 
-# Clean up the output from the toolkit and put it into the .cc file
-mv ${MATCHER}.d ${MATCHER_CC}
-${UNGENERATE} ${MATCHER_CC}
-cat ${MATCHER_CC} | awk '
+# Clean up the toolkit output and rename it.
+${UNGENERATE} "${MATCHER}.d"
+cat "${MATCHER}.d" | awk '
 	/#line.*decoder\.m"/ {
 		line = $2;
 		print $1 " " (line-1) " " $3;
@@ -99,5 +78,5 @@ cat ${MATCHER_CC} | awk '
 		sub(/char \*MATCH_name/, "const &");
 		sub(/char \*name = MATCH_name;/, "const &");
 		print;
-	}' > ${SCRATCH}
-mv ${SCRATCH} ${MATCHER_CC}
+	}' > "${OUTPUT}"
+rm "${MATCHER}.d"
